version: '3'
services:
  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    networks:
      - testnet
    command: mvn clean test
networks:
  testnet:
